### ISSUE TITLE
Grammar Issues in second paragraph

### ISSUE THREAD

**Issue by geerc** [liux2/liux2.github.io#1]
You might have the experiences that Skype your friends or your families at some case. - confusing, not sure what you are trying to say here

We didn’t have such a popular technology to convenient us. - delete 'to convenient us'

Back to that ancient time, if people want(ed) to talk to their families from far away, the(eir) choices were telephone and emails. - replace 'back to' with 'back in', replace 'telephone and emails' with 'telephone or email'

If managers want(ed) to have a meeting with others, they might have to travel across the country, or even (an) ocean. - delete 'with others'

That was very inconvenient for us. - delete this sentence, its implied in the previous sentence

We had to pay a lot to get our telephones connected, it was much expensive if it was an international conversation. - replace 'We had to pay a lot' with 'It was expensive to', delete 'out', replace 'much' with 'very'

For managers, after a long-time travel, they would lose all the energies they had. - replace 'energies' with 'energy, I would suggest moving this sentence to after you talk about the long plane flights

I had the similar experience, too. - replace 'the' with 'a', delete too

**Comment by liux2** [comment]
I did a lot revision here, just came back from gateway. Sorry, I am still working on improve my English  T_T
