### ISSUE TITLE
Grammar issues in thrid paragraph

### ISSUE THREAD

**Issue by geerc** [liux2/liux2.github.io#2]
We didn’t even have low-speed Internet at that time because I was living in a small town in China, where we didn’t have a good infrastructure. The only thing we had was an extremely low-speed Internet connection and telephones. - this is just a little confusing because you said you didn't have low-speed internet in the first sentence, then said you did in the third

My house was far away from my grandparents’. Apparently, the telephone couldn’t fulfill my grandparents’ wish to see me in person. - combine these sentences by putting ', and' after 'grandparents''

That was a problem until the populariz(ation) and commercializ(ation) of high-speed Internet and video chat.

**Comment by liux2** [comment]
That is a hyperbole. It means the speed is very very very slow. 

I have revised the sentence according to your second suggestion.
